language: ruby
rvm:
  - 1.9.3
install: true
before_script:
  - rvm alias delete default
  - hash -r
  - ./install
  - rvm-smile
  - git submodule init
  - git submodule update
  - gem install dtf
script: dtf --text rvm-test/fast/*
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#rvm"
  email:
    recipients:
      - mpapis@gmail.com
      - me@deryldoucette.com
    on_failure: change
